main_app/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    #Printers
    path('printers/', views.printers_index, name = 'printers_index'),
    path('printers/<int:printer_id>/', views.printer_details, name = "printer_details"),
    path('printers/create', views.PrinterCreate.as_view(), name='printer_create'),
    path('printers/<int:pk>/update', views.PrinterUpdate.as_view(), name='printer_update'),
    path('printers/<int:pk>/delete', views.PrinterDelete.as_view(), name='printer_delete'),
    #Prints
    path('printers/<int:printer_id>/add_print/', views.add_print, name = 'add_print'),
    #Filament
    path('filaments/', views.filaments_index, name = 'filament_index'),
    path('filaments/<int:filament_id>/', views.filament_details, name = "filament_details"),
    path('filaments/create', views.FilamentCreate.as_view(), name='filament_create'),
    path('filaments/<int:pk>/update', views.FilamentUpdate.as_view(), name='filament_update'),
    path('filaments/<int:pk>/delete', views.FilamentDelete.as_view(), name='filament_delete'),
]

threedprintercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main_app.urls'))
]

main_app/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
# Import the User
from django.contrib.auth.models import User

# Create your models here.
FILAMENTS = (
    ('PLA', 'PLA'),
    ('PLA+', 'PLA+'),
    ('PTEG', 'PTEG'),
    ('ABS', 'ABS'),
    ('NY', 'Nylon'),
)
    
class Filament(models.Model):
    maker= models.CharField(max_length=50)
    material= models.CharField(max_length=4, choices=FILAMENTS, default=FILAMENTS[0][0])
    color= models.CharField(max_length=50)
    diameter= models.DecimalField( max_digits=3, decimal_places=2, default=1.75)
    weight= models.IntegerField()
    temps = models.TextField(max_length=150)

    def __str__(self):
        return self.material

    def get_absolute_url(self):
        return reverse("filament_details", kwargs={"filament_id": self.id})

COMPLETED = (
    ("1", 'Success'),
    ("0", 'Failure')
)

class Print(models.Model):
    print = models.CharField(max_length=50)
    print_time = models.IntegerField()
    #filament =  models.CharField(max_length=4, choices=FILAMENTS, default=FILAMENTS[0][0])
    nozzle_temp = models.IntegerField(default=200)
    nozzle_size = models.DecimalField( max_digits=3, decimal_places=2, default=0.4)
    layer_height= models.DecimalField(max_digits=3, decimal_places=2, default=0.4)
    other_settings = models.TextField(max_length=250, default='Additional slicer settings')
    completed = models.CharField(max_length=1, choices=COMPLETED, default=COMPLETED[0][0])
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # printer = models.ForeignKey(Printer, on_delete = models.SET_DEFAULT, default= "unavailable")
    def __str__(self):
        hours = self.print_time // 60
        minutes = self.print_time % 60
        print_time_string ="{}h:{}m".format(hours, minutes)
        if self.completed == "1":
            return f'{self.print} on {self.printer} printed successfully on {self.date.strftime("%d/%m/%Y %H:%M:%S")} and took {print_time_string}'
        else:
            return f'{self.print} on {self.printer} failed on {datetime.now()} after {print_time_string}'
    class Meta:
        ordering = ['-date']
    def get_absolute_url(self):
        return reverse("print_details", kwargs={"print_id": self.id})

class Printer(models.Model):
    #     maker, model, build_volume_X,build_volume_Y,build_volume_Z , print_materials, usage
    maker = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    build_volume_X = models.IntegerField()
    build_volume_Y = models.IntegerField()
    build_volume_Z = models.IntegerField()
    print_materials = models.ManyToManyField(Filament)
    usage = models.TextField(max_length=150)
    prints = models.ManyToManyField(Print)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.model

    def get_absolute_url(self):
        return reverse("printer_details", kwargs={"printer_id": self.id})

main_app/forms.py
from pyexpat import model
from statistics import mode
from django.forms import ModelForm
from .models import Print

class PrintForm(ModelForm):
    class Meta:
        model = Print
        fields = ('print', 'print_time', 'filament', 'nozzle_temp', 'nozzle_size', 'layer_height', 'other_settings', 'completed' )

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Printer, Filament
from .forms import PrintForm

# Create your views here.
def home (request):
    return render( request, 'home.html', {'page_name' : 'Home'})

def about (request):
    return render( request, 'about.html', {'page_name' : 'About'})

# class Printer:
#     def __init__ (self, maker, model, build_volume_X, build_volume_Y, build_volume_Z, print_materials, usage):
#         self.maker = maker
#         self.model = model
#         self.build_volume_X = build_volume_X
#         self.build_volume_Y = build_volume_Y
#         self.build_volume_Z = build_volume_Z
#         self.print_materials = print_materials
#         self.usage = usage


# printers =[
#     Printer('Voxelab', 'Aquila', 220,220,250, ['PLA','ABS','PETG', 'Nylon'],"Models" ),
#     Printer('Creality', 'Ender 3 v2', 220,220,250, ['PLA','ABS','PETG', 'Nylon'], 'parts' ),
#     Printer('ANYCUBIC', 'Mega S', 210, 210, 205, ['PLA','ABS','PETG', 'Nylon'], 'parts' ),
# ]


def printers_index (request):
    printers = Printer.objects.all()
    return render( request, 'printers/index.html', {'page_name' : 'Printers Collection', 'printers':printers})

def printer_details(request, printer_id):
    printer = Printer.objects.get(id=printer_id)
    print_form = PrintForm
    return render (request, 'printers/details.html', {'page_name' : printer.model+"'s details", 'printer': printer, 'print_form':print_form})

def add_print(request, printer_id):
    form = PrintForm(request.POST)
    if form.is_valid():
        new_print = form.save(commit=False)
        new_print.printer_id = printer_id
        new_print.save()
    return redirect ('printer_details', printer_id=printer_id)

#classes instead of functions

class PrinterCreate(CreateView):
    model = Printer
    fields = '__all__'
class PrinterUpdate(UpdateView):
    model = Printer
    fields = ('build_volume_X', 'build_volume_Y', 'build_volume_Z', 'print_materials', 'usage')
class PrinterDelete(DeleteView):
    model = Printer
    success_url = '/printers/'


# FILAMENTS
def filaments_index (request):
    filaments = Filament.objects.all()
    return render( request, 'filaments/index.html', {'page_name' : 'Filaments Collection', 'filaments':filaments})

def filament_details(request, filament_id):
    filament = Filament.objects.get(id=filament_id)
    return render (request, 'filaments/details.html', {'page_name' : filament.maker+"'s filament details", 'filament': filament})


#classes instead of functions

class FilamentCreate(CreateView):
    model = Filament
    fields = '__all__'

class FilamentUpdate(UpdateView):
    model = Filament
    fields = ('material', 'color', 'diameter', 'weight', 'temps')

class FilamentDelete(DeleteView):
    model = Filament
    success_url = '/filaments/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{page_name}} | 3D Printer Collector</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    </head>
    <body>
        <header class="navbar-fixed">
            <ul id="adddropdown" class="dropdown-content">
                <li><a href="{% url 'printer_create' %}">Add a printer</a></li>
                <li><a href="{% url 'filament_create' %}">Add a filament</a></li>
            </ul>
            <ul id="viewdropdown" class="dropdown-content">
                <li><a href="/printers">View my Printers</a></li>
                <li><a href="/filaments">View my filaments</a></li>
                <li><a href="/prints">View my prints</a></li>
            </li>
            </ul>
            <nav class= "orange darken-1">
                <div class="nav-wrapper">
                    <ul>
                        <li>
                            <a href="/" class="left brand-logo">3D Printer Collector</a>
                        </li>
                    </ul>
                    <ul class="right">
                        <li>
                            <a href="/about">About</a>
                        </li>
                        <li>
                            <a class="dropdown-trigger" href="#!" data-target="adddropdown">Add<i class="material-icons right">arrow_drop_down</i></a>
                        </li>
                        <li>
                            <a class="dropdown-trigger" href="#!" data-target="viewdropdown">View<i class="material-icons right">arrow_drop_down</i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <main class="container">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="page-footer orange darken-1">
            <div class="right">
                All Rights Reserved, &copy; 2022 3D Printer Collector &nbsp;
            </div>
        </footer>
        <script async defer>
            {% comment %} drop down code {% endcomment %}
            var dropdowns = document.querySelectorAll('.dropdown-trigger')
            for (var i = 0; i < dropdowns.length; i++){
                M.Dropdown.init(dropdowns[i]);
            }
            
        </script>
    </body>
</html>

main_app/templates/filaments/details.html
{% extends 'base.html' %}

{% block content %}
<h1>Filament Details</h1>

('material', 'color', 'diameter', 'weight', 'temps')
<div class="card">
    <div class = "card-content">
        <span class = "card-title h2"> {{filament.maker}} {{printer.material}}</span>
        <img src="" alt="{{filament.maker}} {{filament.material}} image">
        <p> Maker: {{filament.maker}}</p>
        <p> Material: {{filament.material}}</p>
        <p> Color: {{filament.color}}</p>
        <p> Diameter: {{filament.diameter}}</p>
        <p> Weight: {{filament.weight}}</p>
        <p> Optimal temps: {{filament.temps}}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'filament_update' filament.id %}">Edit</a>
        <a href="{% url 'filament_delete' filament.id %}">Delete</a>
</div>
<script>
    const selectFilament = document.getElementById('id_material')
    M.FormSelect.init(selectFilament)
</script>
{% endblock %}

main_app/templates/filaments/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Index of filaments</h1>
    {% for filament in filaments %}
    <a href="/filaments/{{ filament.id }}">
        <div class="card">
            <div class = "card-content">
                <span class = "card-title h2"> {{filament.maker}} {{filament.material}}</span>
                <img src="" alt="{{filament.maker}} {{filament.material}} image">
                <p> Maker: {{filament.maker}}</p>
                <p> Material: {{filament.material}}</p>
                <p> Color: {{filament.color}}</p>
                <p> Diameter: {{filament.diameter}}</p>
                <p> Weight: {{filament.weight}}</p>
                <p> Optimal temps: {{filament.temps}}</p>
            </div>
        </div>
    </a>
    {% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to the 3D printer collector website!</h1>
{% endblock %}

main_app/templates/main_app/filament_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Filament</h1>    
<h4> Are you sure you want to delete <span> {{object.name}} </span></h4>

<form action-"" method = "POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Delete">
    <a class= "btn blue" href="{% url 'filament_details' object.id %}"> cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/filament_form.html
{% extends 'base.html' %}
{% block content %}
    {% if object %}
    <h1> Edit filament</h1>
    <h4>{{object.name}}</h4>
    {% else %}
    <h1>Add new filament</h1>
    {% endif %}

        <form action="" method="POST">
            {% csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            {% if object %}
            <input class="btn yellow" type="submit" value="Edit filament">
            {% else %}
            <input class="btn green" type="submit" value="Add filament">
            {% endif %}
        </form>
{% endblock  %}

main_app/templates/main_app/printer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Printer</h1>    
<h4> Are you sure you want to delete <span> {{object.name}} </span></h4>

<form action-"" method = "POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Delete">
    <a class= "btn blue" href="{% url 'printer_details' object.id %}"> cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/printer_form.html
{% extends 'base.html' %}
{% block content %}
    {% if object %}
    <h1> Edit printer</h1>
    <h4>{{object.name}}</h4>
    {% else %}
    <h1>Add new printer</h1>
    {% endif %}

        <form action="" method="POST">
            {% csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            {% if object %}
            <input class="btn yellow" type="submit" value="Edit printer">
            {% else %}
            <input class="btn green" type="submit" value="Add printer">
            {% endif %}
        </form>
{% endblock  %}

main_app/templates/printers/details.html
{% extends 'base.html' %}

{% block content %}
<h1>Printer Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class = "card-content">
                <span class = "card-title h2"> {{printer.maker}} {{printer.model}}</span>
                <img src="" alt="{{printer.maker}} {{printer.model}} image">
                <p> Maker: {{printer.maker}}</p>
                <p> Model: {{printer.model}}</p>
                <p> Build volume (X,Y,Z): <span>{{printer.build_volume_X}}x{{printer.build_volume_Y}}x{{printer.build_volume_Z}} mm</span></p>
                <p> Print materials: {{printer.print_materials}}</p>
                <p> Usage: {{printer.usage}}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'printer_update' printer.id %}">Edit</a>
                <a href="{% url 'printer_delete' printer.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_print' printer.id %}" method="post">
            {% csrf_token %}
            {{print_form.as_p}}
            <input class="btn" type="submit" value="Add Print">
        </form>
        
        <table class="stripped">
            <thead>
                <tr>

                    <th>Print</th>
                    <th>Filament</th>
                    <th>Nozzle temp</th>
                    <th>Nozzle size</th>
                    <th>Layer Height</th>
                    <th>Other Settings</th>
                    <th>Print Time (in mins)</th>
                    <th>Result</th>
                    {% comment %} maybe have photo field here for each print{% endcomment %}
                </tr>
            </thead>
            <tbody>
                {% for print in printer.print_set.all %}
                
                {% comment %} {% with hours = print.print_time // 60
                minutes = print.print_time % 60
                print_time_string ="{}h:{}m".format(hours, minutes)%} {% endcomment %}
                    
                
                    <tr>
                        <td>{{print.print}}</td>
                        <td>{{print.filament}}</td>
                        <td>{{print.nozzle_temp}}</td>
                        <td>{{print.nozzle_size}}</td>
                        <td>{{print.layer_height}}</td>
                        <td>{{print.other_settings}}</td> 
                        <td>{{print.print_time}}</td> 
                        <td>{{print.get_completed_display}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    const selectFilament = document.getElementById('id_filament')
    M.FormSelect.init(selectFilament)
</script>
{% endblock %}

main_app/templates/printers/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Index of 3D printers</h1>
    {% for printer in printers %}
    <a href="/printers/{{ printer.id }}">
        <div class="card">
            <div class = "card-content">
                <span class = "card-title"> {{printer.model}}</span>
                <img src="" alt="{{printer.model}} image">
                <p> Maker: {{printer.maker}}</p>
                <p> Model: {{printer.model}}</p>
                <p> Build volume (X,Y,Z): <span>{{printer.build_volume_X}}x{{printer.build_volume_Y}}x{{printer.build_volume_Z}} mm</span></p>
                <p> Print materials: {{printer.print_materials}}</p>
                <p> Usage: {{printer.usage}}</p>
            </div>
        </div>
    </a>
    {% endfor %}

{% endblock %}